module.exports = {
  streams: [
    {
      index: 0,
      codec_name: 'h264',
      codec_long_name: 'H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10',
      profile: 'High',
      codec_type: 'video',
      codec_time_base: '1/48',
      codec_tag_string: '[0][0][0][0]',
      codec_tag: '0x0000',
      width: 1920,
      height: 1080,
      coded_width: 1920,
      coded_height: 1088,
      has_b_frames: 2,
      sample_aspect_ratio: '1:1',
      display_aspect_ratio: '16:9',
      pix_fmt: 'yuv420p',
      level: 40,
      color_range: 'unknown',
      color_space: 'unknown',
      color_transfer: 'unknown',
      color_primaries: 'unknown',
      chroma_location: 'left',
      field_order: 'progressive',
      timecode: 'N/A',
      refs: 1,
      is_avc: 'true',
      nal_length_size: 4,
      id: 'N/A',
      r_frame_rate: '24/1',
      avg_frame_rate: '24/1',
      time_base: '1/1000',
      start_pts: 0,
      start_time: 0,
      duration_ts: 'N/A',
      duration: 'N/A',
      bit_rate: 'N/A',
      max_bit_rate: 'N/A',
      bits_per_raw_sample: 8,
      nb_frames: 'N/A',
      nb_read_frames: 'N/A',
      nb_read_packets: 'N/A',
      tags: {
        'BPS-eng': '4421546',
        'DURATION-eng': '01:29:59.625000000',
        'NUMBER_OF_FRAMES-eng': '129591',
        'NUMBER_OF_BYTES-eng': '2984336571',
        '_STATISTICS_WRITING_APP-eng': "mkvmerge v45.0.0 ('Heaven in Pennies') 64-bit",
        '_STATISTICS_WRITING_DATE_UTC-eng': '2020-07-10 04:00:23',
        '_STATISTICS_TAGS-eng': 'BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES'
      },
      disposition: {
        default: 1,
        dub: 0,
        original: 0,
        comment: 0,
        lyrics: 0,
        karaoke: 0,
        forced: 0,
        hearing_impaired: 0,
        visual_impaired: 0,
        clean_effects: 0,
        attached_pic: 0,
        timed_thumbnails: 0
      }
    },
    {
      index: 1,
      codec_name: 'eac3',
      codec_long_name: 'ATSC A/52B (AC-3, E-AC-3)',
      profile: 'unknown',
      codec_type: 'audio',
      codec_time_base: '1/48000',
      codec_tag_string: '[0][0][0][0]',
      codec_tag: '0x0000',
      sample_fmt: 'fltp',
      sample_rate: 48000,
      channels: 6,
      channel_layout: 'unknown',
      bits_per_sample: 0,
      dmix_mode: '-1',
      ltrt_cmixlev: '-1.000000',
      ltrt_surmixlev: '-1.000000',
      loro_cmixlev: '-1.000000',
      loro_surmixlev: '-1.000000',
      id: 'N/A',
      r_frame_rate: '0/0',
      avg_frame_rate: '0/0',
      time_base: '1/1000',
      start_pts: 0,
      start_time: 0,
      duration_ts: 'N/A',
      duration: 'N/A',
      bit_rate: 'N/A',
      max_bit_rate: 'N/A',
      bits_per_raw_sample: 'N/A',
      nb_frames: 'N/A',
      nb_read_frames: 'N/A',
      nb_read_packets: 'N/A',
      tags: {
        language: 'eng',
        'BPS-eng': '256000',
        'DURATION-eng': '01:29:59.744000000',
        'NUMBER_OF_FRAMES-eng': '168742',
        'NUMBER_OF_BYTES-eng': '172791808',
        '_STATISTICS_WRITING_APP-eng': "mkvmerge v45.0.0 ('Heaven in Pennies') 64-bit",
        '_STATISTICS_WRITING_DATE_UTC-eng': '2020-07-10 04:00:23',
        '_STATISTICS_TAGS-eng': 'BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES'
      },
      disposition: {
        default: 1,
        dub: 0,
        original: 0,
        comment: 0,
        lyrics: 0,
        karaoke: 0,
        forced: 0,
        hearing_impaired: 0,
        visual_impaired: 0,
        clean_effects: 0,
        attached_pic: 0,
        timed_thumbnails: 0
      }
    },
    {
      index: 2,
      codec_name: 'subrip',
      codec_long_name: 'SubRip subtitle',
      profile: 'unknown',
      codec_type: 'subtitle',
      codec_time_base: '0/1',
      codec_tag_string: '[0][0][0][0]',
      codec_tag: '0x0000',
      width: 'N/A',
      height: 'N/A',
      id: 'N/A',
      r_frame_rate: '0/0',
      avg_frame_rate: '0/0',
      time_base: '1/1000',
      start_pts: 0,
      start_time: 0,
      duration_ts: 5399744,
      duration: 5399.744,
      bit_rate: 'N/A',
      max_bit_rate: 'N/A',
      bits_per_raw_sample: 'N/A',
      nb_frames: 'N/A',
      nb_read_frames: 'N/A',
      nb_read_packets: 'N/A',
      tags: {
        language: 'eng',
        'BPS-eng': '76',
        'DURATION-eng': '01:29:52.542000000',
        'NUMBER_OF_FRAMES-eng': '1802',
        'NUMBER_OF_BYTES-eng': '51283',
        '_STATISTICS_WRITING_APP-eng': "mkvmerge v45.0.0 ('Heaven in Pennies') 64-bit",
        '_STATISTICS_WRITING_DATE_UTC-eng': '2020-07-10 04:00:23',
        '_STATISTICS_TAGS-eng': 'BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES'
      },
      disposition: {
        default: 0,
        dub: 0,
        original: 0,
        comment: 0,
        lyrics: 0,
        karaoke: 0,
        forced: 0,
        hearing_impaired: 0,
        visual_impaired: 0,
        clean_effects: 0,
        attached_pic: 0,
        timed_thumbnails: 0
      }
    },
    {
      index: 3,
      codec_name: 'subrip',
      codec_long_name: 'SubRip subtitle',
      profile: 'unknown',
      codec_type: 'subtitle',
      codec_time_base: '0/1',
      codec_tag_string: '[0][0][0][0]',
      codec_tag: '0x0000',
      width: 'N/A',
      height: 'N/A',
      id: 'N/A',
      r_frame_rate: '0/0',
      avg_frame_rate: '0/0',
      time_base: '1/1000',
      start_pts: 0,
      start_time: 0,
      duration_ts: 5399744,
      duration: 5399.744,
      bit_rate: 'N/A',
      max_bit_rate: 'N/A',
      bits_per_raw_sample: 'N/A',
      nb_frames: 'N/A',
      nb_read_frames: 'N/A',
      nb_read_packets: 'N/A',
      tags: {
        language: 'spa',
        'BPS-eng': '76',
        'DURATION-eng': '01:29:57.500000000',
        'NUMBER_OF_FRAMES-eng': '1920',
        'NUMBER_OF_BYTES-eng': '51818',
        '_STATISTICS_WRITING_APP-eng': "mkvmerge v45.0.0 ('Heaven in Pennies') 64-bit",
        '_STATISTICS_WRITING_DATE_UTC-eng': '2020-07-10 04:00:23',
        '_STATISTICS_TAGS-eng': 'BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES'
      },
      disposition: {
        default: 0,
        dub: 0,
        original: 0,
        comment: 0,
        lyrics: 0,
        karaoke: 0,
        forced: 0,
        hearing_impaired: 0,
        visual_impaired: 0,
        clean_effects: 0,
        attached_pic: 0,
        timed_thumbnails: 0
      }
    }
  ],
  format: {
    filename: '/home/nathan/Videos/Palm.Springs.2020.1080p.AVC.EAC3.6ch.mkv',
    nb_streams: 4,
    nb_programs: 0,
    format_name: 'matroska,webm',
    format_long_name: 'Matroska / WebM',
    start_time: 0,
    duration: 5399.744,
    size: 3158577248,
    bit_rate: 4679595,
    probe_score: 100,
    tags: {
      encoder: 'libebml v1.3.10 + libmatroska v1.5.2',
      creation_time: '2020-07-10T04:00:23.000000Z'
    }
  },
  chapters: []
};