# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint-and-test:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@master
       - name: Install, Lint and Test
         uses: actions/setup-node@master
         with:
           node-version: '14'
       - run: yarn install
       - run: yarn lint
       - run: yarn test
         
       
