name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  lint-and-test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Install, Lint and Test
          uses: actions/setup-node@master
          with:
            node-version: '14'
        - run: yarn install
        - run: yarn lint
        - run: yarn test

